// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.github.prusov;

import com.github.prusov.Book;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Book_Roo_Configurable {
    
    declare @type: Book: @Configurable;
    
}
